### PR TITLE
Add copyBodyClasses function for 1.11.0

### LINKED ISSUE #118: How to force/add class attribute to the BODY in the IFrame used for printing.
> Hi, It is not an Issue, it a question itself, Are any way of add class tribute information to the BODY in the IFrame used for Printing?

I am using to print part of a page , I'm using Metro boostrap so the BODY of the principal page has the class="metro" attribute, but this attribute it is not replicated to the BODY of the IFrame used.
As a result, grid system of metro it is not respected on the Iframe

I'm not and expert, sorry if the question it is irrelevant.

Thanks in advance for any help

Actual situation:
captureprintthis001

Expected (adding class="metro" in Console )
captureprintthis002

Js code calling the plugin

    $("[uc='rfsint']").printThis({
      debug: true,               // show the iframe for debugging
      importCSS: true,            // import page CSS
      importStyle: true,         // import style tags
      printContainer: true,       // grab outer container as well as the contents of the selector
      loadCSS: "",  // path to additional css file - use an array [] for multiple
      pageTitle: "EMI Visualizer_" + RFSID,              // add title to print page
      removeInline: false,        // remove all inline styles from print elements
      printDelay: 333,            // variable print delay; depending on complexity a higher value may be necessary
      header: "",               // prefix to html
      footer: "",               // postfix to html
      base: false,               // preserve the BASE tag, or accept a string for the URL
      formValues: true,           // preserve input/form values
      canvas: false,              // copy canvas elements (experimental)
      doctypeString: "",       // enter a different doctype for older markup
      removeScripts: false        // remove script tags from print content
    });

### PR DESCRIPTION
**Pull request by oculus42**
Add copyBodyClasses function, disabled by default.

Resolves #118

### CODE REVIEW

**Comment by jasonday** [comment]
Thinking out loud, should it work for body or html elements? Something like
false, body, html, or both?

**Comment by oculus42** [comment]
I considered accepting a selector or an array of elements, but didn't want to go too far, because it could introduce errors. Should the condition handle `<html>` and `<body>`, have two conditions, or support an array of elements?

**Comment by jasonday** [comment]
I worry about going beyond <html> and <body> due to additional complexities
for a likely minimal use case.

As for implementation, I don't have a strong opinion.

On Jul 29, 2017 1:22 PM, "Samuel Rouse" <notifications@github.com> wrote:

I considered accepting a selector or an array of elements, but didn't want
to go too far, because it could introduce errors. Should the condition
handle <html> and <body>, have two conditions, or support an array of
elements?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/jasonday/printThis/pull/119#issuecomment-318845567>,
or mute
the thread

**Comment by oculus42** [comment]
Still not really sure about this implementation... Should we just have a `copyTagClasses` feature that does both? The per-tag setting seems like excessive config for most cases...

What do you think of a `copyTagClasses` which if true copies body, and tests for `"b" and `"h"`, so you could write out `"html, body"` or `"bh"` or `"h"`?

**Comment by jasonday** [comment]
I agree, I'm not sure about implementation either. I'm wondering if we are over-engineering this use case. 

- Do we need both?
- Should we be doing this dynamically? Meaning, I'm wondering if we simply have an `addBodyClass` option which accepts a string, and the user can either manually input a value or dynamically grab the body classes from the page within their own code/plugin call. 

Example:
`$('button').on('click', function(){
    var myBody = $('body').attr('class');
    $('div').printThis({
        addBodyClass: myBody
    });
});`

**Comment by oculus42** [comment]
I created an alternative which I think is better: `copyTagClasses` on PR #123

**Pull request merged**
