### PR TITLE
Proposed fix for missing canvas content

### LINKED ISSUE #32: Google maps not showing route line
When using a Bootstrap modal to display a map with a form (so the user can generate directions) the route line doesn't show (in Chrome, Safari, and Firefox -- all Mac OSX 10.9).

It displays in Chrome's Print Preview (printing from the browser menu) but not when using printThis.

My first assumption was it was a scope thing as I was creating a new map object when the modal was launched (thereby showing no route line when the modal is re-opened), but even after changing this the route line still appears in the modal but not when printing.

Any thoughts would be most welcome.

Here's the JS I'm using to trigger printThis:

``` javascript
$('#print_directions').on('click', function(ev) {
        ev.preventDefault();

        $('#printSection').printThis( {
                debug: false,
                importCSS:true,
                printContainer: false,
                pageTitle: "Getting here",
                printDelay: 333,
                header: null,
            });
    });
});
```

For example, here's Print Preview in Chrome as if I were printing normally;
image

And here's the Print Preview when using printThis.
image

### PR DESCRIPTION
**Pull request by oculus42**
Proposed fix for canvas content not being duplicated.

I don’t know if we want this to be enabled on a flag, or pursue a method that doesn’t edit the markup. 

Feedback appreciated.

Fixes #32 

Example:
http://fiddle.jshell.net/_sir/5aGhx/11/show/

### CODE REVIEW

**Comment by jasonday** [comment]
This looks really promising Sam. 

I'm missing something here, as I'm not sure of the reference to editing markup.
> pursue a method that doesn’t edit the markup

**Comment by oculus42** [comment]
I'm adding the data-printthis to the *original* page so I can reference the
same canvas elements once we have a copy in the iframe. I could go behind
and remove the data attributes after finding them, but there might be a way
to match them without the attributes. It was just a much easier/safer
solution.

**Comment by jasonday** [comment]
I think your proposal works and is a safe mechanism (although isn't fully one-way) - I'd say add it as a flag set to false, with additional details in the readme.

**Comment by jasonday** [comment]
Also wondering if we should tag it as 'experimental' as we haven't tested with multiple canvas elements, or different types of canvas elements.

**Pull request merged**
