### PR TITLE
Add removeScripts option

### LINKED ISSUE #104: Add ability to strip script tags from print content
Add an option to remove script tags from the print area before copying it to the print iframe.

We have seen this a couple of times in issues, so we might as well provide the mechanism.

I'm thinking "removeScripts" or "stripScripts".

It would default to disabled in 1.x, and probably on by default in 2.x?

Thoughts?

### PR DESCRIPTION
**Pull request by oculus42**
Rework the inject functionality to support removing scripts before
inserting into new document.
Removed $.fn.outer
Fixes #104

### CODE REVIEW

**Comment by oculus42** [comment]
Wasn't sure if this should be kicked to 2.0.0 because of removing `$.fn.outer`. While it is undocumented, it would break code for anyone using it outside of `printThis`.

**Comment by oculus42** [comment]
Also, I've tested on Safari, Firefox and Chrome (on Mac), with this Fiddle: https://fiddle.jshell.net/_sir/cnm6v3jd/

**Comment by jasonday** [comment]
Not that it's impossible, but it's probably a small use case for outside usage of `$.fn.outer`.

**Comment by jasonday** [comment]
In looking at the code, should we rework to flip `importStyle` to `removeStyle` and do this from your cloned content? I'm just wondering if we have some efficiencies we would utilize in this cloned object.

**Comment by oculus42** [comment]
It would make sense, I think. Changing the option name would require a bump to 2.0, so I would recommend we push 1.10.0 and we can make the improvements so people who are on 1.x can still get the removeScript behavior. That also lets us re-evaulate the defaults if need be

I also have some improvements for 2.x that could be brought in on the 2.x branch, allowing for more incremental improvements rather than just a giant hit.

**Comment by jasonday** [comment]
Sounds like a plan.

**Pull request merged**
