### PR TITLE
Inherit baseurl

### PR DESCRIPTION
**Pull request by Geezerdiamond**
Added a new option to inherit the BASE tag exactly from the parent.

### CODE REVIEW

**Comment by jasonday** [comment]
How have you tested this change?
Does it resolve?:
- https://github.com/jasonday/printThis/issues/72
- https://github.com/jasonday/printThis/issues/61

**Comment by Geezerdiamond** [comment]
Hi Jason.

Yes, I've tested this and it's currently in use. I'm sure it fixes those issues as they're pretty much the same issue I had and the reason for the code change.

One thing you may want to consider, I've set my new param to default to true but you may want it to be false by default so as not to change any current behaviour (and break people's existing workarounds).

Cheers,
Matt

**Comment by Geezerdiamond** [comment]
Hi again,

I just noticed the word "How" at the start of your message; I didn't exactly cover that in my response due to misreading!

As per issue 72, I also had an additional path element to my application and the BASE tag took care of that. Following the change, my images and CSS correctly load in my printed DIV and I compared before and after using Chrome's inspector.

As I mentioned, it is now in use in my application and working perfectly. Thanks for creating the plug-in in the first place; it got me out of a hole! :-)

Cheers,
Matt

**Comment by oculus42** [comment]
Looks good. Appears to be backward compatible and leaves you the options to later check for an provided opts.base string to use.

**Comment by jasonday** [comment]
I agree. I think the default should be changed to false; what do you think
Sam?

**Comment by oculus42** [comment]
@jasonday For backwards compatibility, I agree it should be false by default.

**Comment by Geezerdiamond** [comment]
I've updated that in the code and re-committed.

Cheers,
M

**Pull request merged**
